package cli

import (
	"fmt"
	"io"

	"github.com/bsmartlabs/dev-vault/internal/config"
)

func printMainUsage(w io.Writer) {
	fmt.Fprintln(w, "dev-vault")
	fmt.Fprintln(w, "  Pull/push Scaleway Secret Manager secrets to disk for local development.")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Usage:")
	fmt.Fprintln(w, "  dev-vault [global options] <command> [command options] [args...]")
	fmt.Fprintln(w, "  dev-vault help [command]")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Global options:")
	fmt.Fprintf(w, "  --config <path>   Path to %s. If omitted: search upward from cwd.\n", config.DefaultConfigName)
	fmt.Fprintln(w, "  --profile <name>  Scaleway profile override (uses ~/.config/scw/config.yaml)")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Commands:")
	fmt.Fprintln(w, "  version")
	fmt.Fprintln(w, "  list")
	fmt.Fprintln(w, "  pull")
	fmt.Fprintln(w, "  push")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Hard safety constraints:")
	fmt.Fprintln(w, "  - Refuses to operate on secret names that do not end with '-dev'.")
	fmt.Fprintln(w, "  - Never prints secret payloads.")
	fmt.Fprintln(w, "  - Pull writes files atomically and chmods them to 0600 (on Unix).")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Batch behavior:")
	fmt.Fprintln(w, "  - mapping.mode defaults to both.")
	fmt.Fprintln(w, "  - pull --all includes mapping entries with mapping.mode in {pull, both}.")
	fmt.Fprintln(w, "  - push --all includes mapping entries with mapping.mode in {push, both}.")
	fmt.Fprintf(w, "  - %s\n", explicitModePolicySentence)
	fmt.Fprintln(w, "  - Note: mapping.mode='sync' is accepted as a legacy alias for 'both'.")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Examples:")
	fmt.Fprintln(w, "  dev-vault list --json")
	fmt.Fprintln(w, "  dev-vault pull bweb-env-bsmart-dev --overwrite")
	fmt.Fprintln(w, "  dev-vault push bweb-env-bsmart-dev")
	fmt.Fprintln(w, "  dev-vault pull --config .scw.json bweb-env-bsmart-dev --overwrite")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Notes for automation/LLMs:")
	fmt.Fprintln(w, "  - Global options can be passed either before the command or as command options (e.g. 'pull --config ...').")
	fmt.Fprintln(w, "  - Exit codes: 0=success, 1=runtime error, 2=usage error.")
}

func printVersionUsage(w io.Writer) {
	fmt.Fprintln(w, "Usage:")
	fmt.Fprintln(w, "  dev-vault version")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Prints the build version/commit/date.")
}

func printListUsage(w io.Writer) {
	fmt.Fprintln(w, "Usage:")
	fmt.Fprintln(w, "  dev-vault [--config <path>] [--profile <name>] list [options]")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Lists secrets in the configured Scaleway project/region.")
	fmt.Fprintln(w, "This command always filters to secret names ending with '-dev'.")
	fmt.Fprintln(w, "It never prints secret payloads, only metadata (name/type/path/id).")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Options:")
	fmt.Fprintln(w, "  --config <path>         (optional) Path to .scw.json")
	fmt.Fprintln(w, "  --profile <name>        (optional) Scaleway profile override")
	fmt.Fprintln(w, "  --name-contains <s>     (repeatable) substring filter (AND semantics)")
	fmt.Fprintln(w, "  --name-regex <re>       Go regexp to match names")
	fmt.Fprintln(w, "  --path <p>              Exact Scaleway secret path to match (default: any)")
	fmt.Fprintln(w, "  --type <t>              One of: opaque|key_value|basic_credentials|database_credentials|ssh_key|certificate")
	fmt.Fprintln(w, "  --json                  Output JSON")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Examples:")
	fmt.Fprintln(w, "  dev-vault list")
	fmt.Fprintln(w, "  dev-vault list --json")
	fmt.Fprintln(w, "  dev-vault list --name-contains bweb --name-contains env")
	fmt.Fprintln(w, "  dev-vault list --name-regex '^bweb-env-.*-dev$' --path / --type key_value")
}

func printPullUsage(w io.Writer) {
	fmt.Fprintln(w, "Usage:")
	fmt.Fprintln(w, "  dev-vault [--config <path>] [--profile <name>] pull (--all | <secret-dev> ...) [options]")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Pulls one or more secrets to disk based on .scw.json mapping.")
	fmt.Fprintln(w, "Secrets must exist in mapping and names must end with '-dev'.")
	fmt.Fprintln(w, "Pull reads the latest enabled secret version (Scaleway revision selector: latest_enabled).")
	fmt.Fprintln(w, "Pull writes files atomically and chmods them to 0600 (on Unix).")
	fmt.Fprintln(w, "Never prints secret payloads.")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Options:")
	fmt.Fprintln(w, "  --config <path>   (optional) Path to .scw.json")
	fmt.Fprintln(w, "  --profile <name>  (optional) Scaleway profile override")
	fmt.Fprintln(w, "  --all             Pull all mapping entries with mapping.mode in {pull, both}")
	fmt.Fprintln(w, "  --overwrite       Overwrite existing files (otherwise pull fails if the file exists)")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Formats:")
	fmt.Fprintln(w, "  - mapping.format=raw")
	fmt.Fprintln(w, "    Writes secret bytes as-is.")
	fmt.Fprintln(w, "  - mapping.format=dotenv")
	fmt.Fprintln(w, "    Expects the secret payload to be a JSON object, renders a deterministic .env file:")
	fmt.Fprintln(w, "    - keys sorted lexicographically")
	fmt.Fprintln(w, "    - values quoted")
	fmt.Fprintln(w, "    - newlines and quotes escaped")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Examples:")
	fmt.Fprintln(w, "  dev-vault pull bweb-env-bsmart-dev --overwrite")
	fmt.Fprintln(w, "  dev-vault pull --all --overwrite")
	fmt.Fprintln(w, "  dev-vault pull --config .scw.json bweb-env-bsmart-dev --overwrite")
	fmt.Fprintln(w, "  dev-vault pull bweb-env-bsmart-dev --config .scw.json --overwrite")
}

func printPushUsage(w io.Writer) {
	fmt.Fprintln(w, "Usage:")
	fmt.Fprintln(w, "  dev-vault [--config <path>] [--profile <name>] push (--all | <secret-dev> ...) [options]")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Pushes one or more secrets from disk to Scaleway Secret Manager as a new version.")
	fmt.Fprintln(w, "Secrets must exist in mapping and names must end with '-dev'.")
	fmt.Fprintln(w, "Never prints secret payloads.")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Options:")
	fmt.Fprintln(w, "  --config <path>         (optional) Path to .scw.json")
	fmt.Fprintln(w, "  --profile <name>        (optional) Scaleway profile override")
	fmt.Fprintln(w, "  --all                   Push all mapping entries with mapping.mode in {push, both}")
	fmt.Fprintln(w, "  --yes                   Required when pushing more than one secret (including --all)")
	fmt.Fprintln(w, "  --disable-previous      Disable the previously enabled version when creating the new version")
	fmt.Fprintln(w, "  --description <text>    Optional description for the new version (default is auto-generated)")
	fmt.Fprintln(w, "  --create-missing        Create the secret if it does not exist (requires mapping.type)")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Formats:")
	fmt.Fprintln(w, "  - mapping.format=raw")
	fmt.Fprintln(w, "    Reads file bytes as-is and uploads them as a new secret version.")
	fmt.Fprintln(w, "  - mapping.format=dotenv")
	fmt.Fprintln(w, "    Reads a .env file and uploads a JSON object payload (key_value style).")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Notes:")
	fmt.Fprintln(w, "  - --create-missing creates the secret if absent (requires mapping.type).")
	fmt.Fprintln(w, "  - Secret creation uses mapping.path (default is '/').")
	fmt.Fprintln(w, "  - If more than one secret is being pushed, you must pass --yes.")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Examples:")
	fmt.Fprintln(w, "  dev-vault push bweb-env-bsmart-dev")
	fmt.Fprintln(w, "  dev-vault push bweb-env-bsmart-dev --description 'local refresh'")
	fmt.Fprintln(w, "  dev-vault push --all --yes")
	fmt.Fprintln(w, "  dev-vault push --config .scw.json --all --yes --disable-previous")
}
